# This workflow runs when recieving a "libpinmame-build"
# repository_dispatch event from vpinball/pinmame.

name: pinmame-native
on:
  repository_dispatch:
    types: [ update-libpinmame ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.version.outputs.semver }}
      exists: ${{ steps.version.outputs.exists }}
    steps:
      - id: version
        run: |
          SEMVER="${{ github.event.client_payload.version }}-preview.${{ github.event.client_payload.revision }}"
          EXISTS=$(if [[ $(curl https://api.nuget.org/v3-flatcontainer/pinmame.native/index.json | grep \"${SEMVER}\") ]]; then echo "true"; else echo "false"; fi)
          echo "::set-output name=semver::${SEMVER}"
          echo "::set-output name=exists::${EXISTS}"

  build-nuget:
    runs-on: ubuntu-latest
    needs: [ version ]
    steps:
      - uses: nuget/setup-nuget@v1
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: libpinmame
          run_id: ${{ github.event.client_payload.run_id }}
          repo: vpinball/pinmame
          path: native/nuget
      - name: Pack
        run: |
          cd native/nuget
          mv libpinmame-*-win-x64 libpinmame-win-x64
          mv libpinmame-*-win-x86 libpinmame-win-x86
          mv libpinmame-*-osx-x64 libpinmame-osx-x64
          mv libpinmame-*-linux-x64 libpinmame-linux-x64
          sed -i 's/__VERSION__/${{ needs.version.outputs.semver }}/g' *.nuspec
          nuget pack PinMame.Native.win-x64.nuspec -OutputDirectory nupkg
          nuget pack PinMame.Native.win-x86.nuspec -OutputDirectory nupkg
          nuget pack PinMame.Native.osx-x64.nuspec -OutputDirectory nupkg
          nuget pack PinMame.Native.linux-x64.nuspec -OutputDirectory nupkg
          nuget pack PinMame.Native.nuspec -OutputDirectory nupkg
      - uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: native/nuget/nupkg

  publish:
    runs-on: ubuntu-latest
    needs: [ version, build-nuget ]
    steps:
      - uses: nuget/setup-nuget@v1
      - uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Publish
        run: |
          nuget push PinMame.Native.${{ needs.version.outputs.semver }}.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json
          nuget push PinMame.Native.win-x64.${{ needs.version.outputs.semver }}.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json
          nuget push PinMame.Native.win-x86.${{ needs.version.outputs.semver }}.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json
          nuget push PinMame.Native.osx-x64.${{ needs.version.outputs.semver }}.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json
          nuget push PinMame.Native.linux-x64.${{ needs.version.outputs.semver }}.nupkg -ApiKey ${{ secrets.NUGET_KEY }} -src https://api.nuget.org/v3/index.json

  dispatch:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: VisualPinball/VisualPinball.Engine.PinMAME
          event-type: update-pinmame-native
          client-payload: '{"run_id": "${{ github.run_id }}"}'
